//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edusko.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolDetail
    {
        public long SchoolDetailId { get; set; }
        public long SchoolOwnerId { get; set; }
        public Nullable<long> SchoolBranchId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string SchoolName { get; set; }
        public string Address { get; set; }
        public Nullable<long> SchoolCategoryId { get; set; }
        public Nullable<long> SchoolTypeId { get; set; }
    
        public virtual SchoolOwner SchoolOwner { get; set; }
    }
}
