//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edusko.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolUser
    {
        public long SchoolUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public long SchoolOwnerId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual SchoolOwner SchoolOwner { get; set; }
    }
}
