//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edusko.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolBranch
    {
        public long SchoolBranchId { get; set; }
        public Nullable<long> SchoolDetailId { get; set; }
        public long SchoolTypeId { get; set; }
        public long SchoolCategoryId { get; set; }
        public string SchoolBranchDesc { get; set; }
        public Nullable<long> LocalGovernmentId { get; set; }
    
        public virtual LocalGovernment LocalGovernment { get; set; }
    }
}
