//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edusko.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public long StateId { get; set; }
        public string StateDesc { get; set; }
        public Nullable<long> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
