USE [master]
GO

/****** Object:  Database [Eduskodb]    Script Date: 11/11/2016 5:32:36 PM ******/
CREATE DATABASE [Eduskodb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Eduskodb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Eduskodb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Eduskodb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Eduskodb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Eduskodb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Eduskodb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Eduskodb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Eduskodb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Eduskodb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Eduskodb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Eduskodb] SET ARITHABORT OFF 
GO

ALTER DATABASE [Eduskodb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Eduskodb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Eduskodb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Eduskodb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Eduskodb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Eduskodb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Eduskodb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Eduskodb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Eduskodb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Eduskodb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Eduskodb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Eduskodb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Eduskodb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Eduskodb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Eduskodb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Eduskodb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Eduskodb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Eduskodb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Eduskodb] SET  MULTI_USER 
GO

ALTER DATABASE [Eduskodb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Eduskodb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Eduskodb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Eduskodb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Eduskodb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Eduskodb] SET  READ_WRITE 
GO

