'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SchoolDetail
    Public Property ScholDetailId As Integer
    Public Property SchoolName As String
    Public Property Address As String
    Public Property SchoolBranchId As Integer
    Public Property CountryId As Integer
    Public Property SchoolOwnerSchoolOwnerId As Integer

    Public Overridable Property SchoolOwner As SchoolOwner
    Public Overridable Property SchoolBranches As ICollection(Of SchoolBranch) = New HashSet(Of SchoolBranch)

End Class
