'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SchoolAdmin
    Public Property SchoolAdminId As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Password As String
    Public Property Active As String
    Public Property SchoolOwnerSchoolOwnerId As Integer

    Public Overridable Property SchoolOwner As SchoolOwner

End Class
