'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SchoolOwner
    Public Property SchoolOwnerId As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Username As String
    Public Property Email As String
    Public Property Password As String
    Public Property Address As String
    Public Property PhoneNumber As Integer
    Public Property Active As Byte

    Public Overridable Property SchoolDetails As ICollection(Of SchoolDetail) = New HashSet(Of SchoolDetail)
    Public Overridable Property SchoolAdmins As ICollection(Of SchoolAdmin) = New HashSet(Of SchoolAdmin)

End Class
