'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SchoolBranch
    Public Property SchoolBranchId As Integer
    Public Property SchoolBranchDescription As String
    Public Property SchoolTypeId As Integer
    Public Property SchoolCategoryId As Integer
    Public Property SchoolDetailScholDetailId As Integer

    Public Overridable Property SchoolDetail As SchoolDetail

End Class
